### ISSUE TITLE
Automatically add paragraphs checkbox not working for manual posts

### ISSUE THREAD

**Issue by marpa** [clas-web/connections-hub#31]
Automatically add paragraphs checkbox not working for manual posts.  This should be checked by default.

**Comment by marpa** [comment]
If you update a manual connection post, the "Automatically add paragraphs" checkbox will become de-selected (even if it was selected before the update)

**Comment by cbarto11** [comment]
bb03660c8a1587e1d6f24d660af58ffb6514506a
