### ISSUE TITLE
Contact Info Widget display not correct

### ISSUE THREAD

**Issue by marpa** [clas-web/connections-hub#32]
The Contact Info widget front end display in not working, see:
https://clas-pages.uncc.edu/dena-shenk/
https://clas-pages.uncc.edu/tanure-ojaide/

**Comment by cbarto11** [comment]
Fixed.  The Connection info is now an array and that array was not converted to text properly.
bd5d2c4195752033c3632f27d5f5efbcc66e33f2
0a1ab4819cf405057c61278d11bf1348dd06e95a
