### ISSUE TITLE
Duplicate entries in admin listing page

### ISSUE THREAD

**Issue by marpa** [clas-web/connections-hub#34]
The listing of connection posts on some connections sites have duplicate listings in the admin listing page.  In many cases these duplicate listing have the same ID.

**Comment by atrus1701** [comment]
This problem only happens on the Project Mosaic site, so my guess its one of the 19 plugins or 21 Jetpack modules activated on the site.  Possible courses of action:
- create a test site and install as many of the same plugins / modules as the Project Mosaic site.
- if unable to find the problem this way, put debug code in project mosaic theme and test late at night when the site is probably not being viewed.

**Comment by marpa** [comment]
Is an issue with Project Mosaic site only
