### ISSUE TITLE
Connections between Connection Posts

### ISSUE THREAD

**Issue by marpa** [clas-web/connections-hub#41]
Add support for showing connections between posts (e.g. people) which would be displayed on any given post single page (e.g. person's summary page).  There could be 2 types of connections:

Within connection group
Show all posts (e.g. people) in the same connection group that share connection links

Outside connection group
Show all posts (e.g. people) who share connection links AND are in different connection groups

**Comment by marpa** [comment]
Related people should NOT include the person who is the source of the relations, see:
https://devpages.uncc.edu/connections/people/yildirim-aktas/

Outside connection group relationships are currently including people within the connection group of the source person...

List of related people should be exhaustive.  It is fine to display these in 2-3 columns or separated by spaces (wrapped in css to adjust spacing)

**Comment by atrus1701** [comment]
Done.  Related People plugin:
https://github.com/clas-web/related-people
