### ISSUE TITLE
Sorting connection posts by date not working

### ISSUE THREAD

**Issue by marpa** [clas-web/connections-hub#44]
When viewing all connections in dashboard, sorting connection posts by date not working

**Comment by akforsyt** [comment]
It appears that sorting is intentionally forced to title ascending.  See https://github.com/clas-web/connections-hub/blob/f47e0430124ab5320e7d1361e47587a83a96ba80/functions.php#L94
Sorting was added in this commit 4589d81416b046812f079148107d0321787d38aa

**Comment by akforsyt** [comment]
fixed by 84bb488ccdfb132ea11aa6321ee9394948a01a47
